#AppLifecyclelistener

# ---INICIO Rutas y entorno ---

# URL base de la API de generacion de avatares (DiceBear)
# Publica: https://api.dicebear.com/7.x
# Mi caso docker: http://dicebear:3000/7.x
ai.dicebear.apiUrl=http://dicebear:3000/7.x

# Entorno del Sistema Operativo (windows o linux) requerido para FFmpeg local

# Si se usa windows, especificarlo aqui
# descargarlo y poner el ejecutable en /WEB-INF/bin/windows
# el que viene por default en linux, es arm , configurar entorno y descargar el adecuado tu entorno
os.environment=linux

#Fotos perfil de usuarios
path.profile=/var/nullchats/profiles

#Fotos,Videos de mensajes
path.messaging=/var/nullchats/uploads/messaging

#Ruta base (context path), dejar en blanco si esta en la raiz.
app.baseUrl=/

# Número de hilos para el pool de procesamiento de video
# Recomendacion: No usar más de (Total de Núcleos / 2)
video.processing.threads=2

# Ruta para el archivo honeypot_paths.txt
# (rutas trampa que banean automaticamente)
path.honeypot-paths=/WEB-INF/honeypot_paths.txt

#Archivo de IPs bloqueadas
path.blocked-ips=/var/nullchats/data/blocked-ips.txt

# ---FIN Rutas y entorno ---


# --- INICIO Rate Limiting ---
# (Peticiones por IP)

#LIMITE DE PETICIONES SEGUIDAS EN TIEMPO X
limits.rate.requestLimit=150

#LIMITE específico para recursos Estaticos (.css, .js, imágenes, etc.)
limits.rate.staticRequestLimit=150

#VENTANA DE TIEMPO PARA LAS PETICIONES (segundos)
limits.rate.timeWindowSeconds=60

#Tiempo de BANEO (segundos)
limits.rate.blockDurationSeconds=60

#Extensiones que tendrán su propio contador de peticiones (archivos estáticos)
#Esto evita que cargar estilos y scripts agote el límite de peticiones (Separados por coma)
ratelimit.static.extensions=.css,.js,.png,.jpg,.jpeg,.gif,.ico,.woff,.woff2,.ttf,.svg,.map,.mp4,.webm,.ogg,.webmanifest,.json

#Rutas que también usarán el Rate Limit estático (Separados por coma)
ratelimit.static.paths=/profile-img,/img,/api/csrf-token

#Rutas que tendrán un Rate Limit ultra estricto (Auth, registros, etc.)
ratelimit.strict.paths=/sign_up,/login,/change_password

#Límite estricto de peticiones para las rutas anteriores en la misma ventana de tiempo
limits.rate.strictRequestLimit=15

#IPs de proxies de confianza (separadas por comas)
#Ejemplo: 127.0.0.1,::1,0:0:0:0:0:0:0:1,173.245.48.0/20,103.21.244.0/22
# IPs y rangos de proxies de confianza (Localhost + Redes internas de Docker)(Para que IP.Utils Funcione Bien)
server.trustedProxies=127.0.0.1,::1,0:0:0:0:0:0:0:1,172.16.0.0/12,192.168.0.0/16,10.0.0.0/8
# --- FIN Rate Limiting ---


# --- INICIO Login Fail Attempt ---
#Superados estos limites la IP sera bloqueada permanentemente

#Intentos fallidos
limits.login.maxAttempts=15

#Ventana de tiempo para intentos (segundos)
limits.login.timeWindowSeconds=900
# --- FIN Login Fail Attempt ---


# --- INICIO LOGGER ---

#Extensiones de archivo a ignorar en los logs(separadas por coma, con el punto)
logfilter.ignore.extensions=.css,.js,.png,.jpg,.jpeg,.gif,.ico,.woff,.woff2,.ttf,.svg,.map,.js.map,.css.map,.mp4,.webm,.ogg,.webmanifest,.json

#Rutas que comienzan con... a ignorar (separadas por coma)
# al final agregamos ,/ para ignorar la raiz
logfilter.ignore.paths=/profile-img,/admin-logs,/admin-dashboard,/api/csrf-token,/api/messaging,/blocked-users,/home,/

# ---FIN IPLoggingFilter ---


# --- INICIO EWAF ---

#Por defecto banea en cualquier ruta al instante que haya SQL Injection
#Rutas donde se permite HTML/Scripts (WAF XSS Exemption) - (Separadas por coma)
waf.xss.allowedPaths=/messaging

#Rutas donde se permite SQL Injection - (Separadas por coma)
waf.sqli.allowedPaths=/messaging

#Rutas donde se BLOQUEA la SQL Injection (Error 400) pero NO se banea la IP (se activa contador)
#Útil para formularios públicos propensos a falsos positivos o errores de usuario
waf.sqli.noBanPaths=

#Rate Limiting de SQL Injection en las especificadas en noBanPaths
#Contador de ataque SQLi antes de banear la IP permanentemente
waf.block.maxAttempts=3

#Ventana de tiempo para el contador de ataques SQLi (segundos)
#(3600s = 1 hora)
waf.block.timeWindowSeconds=3600

#Rutas restringidas EXCLUSIVAMENTE para administradores - (Separadas por coma)
security.admin.paths=/admin-block-ip,/admin-logs,/admin_change_password,/admin-manage_users,/delete_user,/toggle_account,/admin-maintenance,/admin-stats,/admin-dashboard,/admin-security

# --- FIN EWAF ---


# -INICIO RESTRICCIONES CUENTA

# Usuarios reservados que no pueden ser registrados (separados por coma)
limits.accounts.reservedUsernames=admin,administrador,administrator,root,system,moderador,moderator,soporte,soport,mod,staff,creator,sistema,anonimo,anonymous

#Límite de caracteres para consultas de búsqueda
limits.search.maxLength=100

#Límite de creación de Usuarios por día desde la misma IP
limits.accounts.perDay=5

#Límite de cambios de contraseña por día (por usuario)
limits.password.changesPerDay=5

# -FIN RESTRICCIONES CUENTA


# -INICIO MENSAJES

#Soporte para descifrar mensajes antiguos (v0, v1, texto plano)
messaging.legacy.encryption.support=false

#Límite de caracteres por mensaje de texto
limits.messages.maxLength=5000

#Límite de mensajes multimedia (fotos/videos) por día
limits.multimediaMessages.perDay=100

#Limite de cantidad de conversaciones
# (si se supera, ya no puede enviar mensajes de texto a pesar que el limite diario sea mas alto)
limits.messages.uniqueRecipients=250

#Límite de mensajes de texto por día
#(si se supera, (texto) aun se podria enviar multimedia si dicho limite es superior)
limits.messages.totalPerDay=800

#-TAMAÑOS MAXIMOS DE SUBIDA en MB:
#Límite "suave" de imagenes, videos en Mensajes
limits.upload.maxFileSizeMB=20

#- FIN MENSAJES

# --- INICIO USER STATUS VALIDATOR ---
# Rutas a ignorar para la validación de estado de usuario (separadas por coma)
# Si un usuario es deshabilitado no podra hacer login, sin embargo si ya tiene la sesion abierta escapa a eso
# Para resolverlo esta el status filter que chequea en cada peticion si el usuario esta bloqueado y le invalida la sesion
# Para mayor rendimiento vamos a ignorar todas estas rutas, ya que messaging tiene un polling constante y solo con escuchar en ese endpoint es suficiente
userstatus.ignore.paths=/profile-img,/api/csrf-token,/get-message-status,/logout
# --- FIN USER STATUS VALIDATOR ---


#AppLifecyclelistener

#AppPrivateConfig

# Clave maestra para cifrar/descifrar mensajes.
security.messaging.masterKey=1LUw27B6wPNibZKrPJGCigV642358rpABg0x22a1dd7cd753ba5c52db23d927fc6ded7025579d


#AppPrivateConfig





